<?php	
	#phpinfo();
	include('./php/connectdb.php');
	include('./pageLayout/head.php');
	include('./pageLayout/pageHeader.php');
	include('./pageLayout/main_body.php');
	include('./pageLayout/about.php');
	include('./pageLayout/footer.php');
?>