CREATE TABLE user(
username VARCHAR(16) PRIMARY KEY,
password VARCHAR(16)
);

CREATE TABLE comment(
id INTEGER PRIMARY KEY AUTOINCREMENT,
review_id INTEGER REFERENCES review,
user_id INTEGER REFERENCES user,
text VARCHAR(5000)
);

CREATE TABLE review(
id INTEGER PRIMARY KEY AUTOINCREMENT,
author_id  INTEGER REFERENCES user,
restaurant_id INTEGER REFERENCES restaurant,
text VARCHAR(15000),
score INTEGER,
CHECK(score > 0),
CHECK(score < 11)
);

CREATE TABLE restaurant(
owner_id INTEGER REFERENCES user,
name VARCHAR(255),
adress VARCHAR(255),
city_id INTEGER REFERENCES city,
country_id INTEGER REFERENCES country 
);

CREATE TABLE country(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(255)
);

CREATE TABLE city(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(255)
);
